# Generated by Django 3.2 on 2021-04-13 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaznici', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telefonnicislo',
            options={'ordering': ['cislo']},
        ),
        migrations.AddField(
            model_name='telefonnicislo',
            name='cislo',
            field=models.PositiveIntegerField(default=111111111, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)], verbose_name='Telefonni číslo'),
        ),
    ]
