# Generated by Django 3.2 on 2021-04-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaznici', '0002_auto_20210413_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=40, verbose_name='Nazev tarifu')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cena tarifu')),
            ],
            options={
                'ordering': ['cena'],
            },
        ),
    ]
