# Generated by Django 3.2 on 2021-05-05 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zakaznici', '0003_tarif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smlouva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_uzavreni', models.DateField(blank=True, null=True, verbose_name='Datum uzavření')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakaznici.mobilnioperator')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakaznici.tarif')),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakaznici.zakaznik')),
            ],
        ),
    ]
