# Generated by Django 3.2 on 2021-05-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaznici', '0004_smlouva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaznik',
            name='druhotne_sluzby',
            field=models.ManyToManyField(blank=True, help_text='Select a secondary service of mobile operator which you use', null=True, to='zakaznici.DruhotneSluzby'),
        ),
    ]
