# Generated by Django 3.2 on 2021-05-06 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaznici', '0005_alter_zakaznik_druhotne_sluzby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilnioperator',
            name='email',
            field=models.PositiveIntegerField(default=111111111, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)], verbose_name='Telefonni číslo'),
        ),
    ]
