# Generated by Django 3.2 on 2021-05-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakaznici', '0007_rename_email_mobilnioperator_podpora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilnioperator',
            old_name='podpora',
            new_name='email',
        ),
    ]
