# Generated by Django 3.2 on 2021-05-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakaznici', '0008_rename_podpora_mobilnioperator_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilnioperator',
            old_name='email',
            new_name='kontakt',
        ),
    ]
