# Generated by Django 3.2 on 2021-05-09 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zakaznici', '0009_rename_email_mobilnioperator_kontakt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smlouva',
            options={'ordering': ['datum_uzavreni']},
        ),
        migrations.AddField(
            model_name='tarif',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zakaznici.mobilnioperator'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cena tarifu'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='ulice',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ulice'),
        ),
    ]
